version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=ocelot_logs
      - SECRET_KEY=dev_secret_key_change_in_production
      - DEBUG=true
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Ocelot Log Service
      - ENVIRONMENT=development
    depends_on:
      - mongodb
    volumes:
      - ../app:/app/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 